# Generated by Django 5.0.7 on 2024-08-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOARD', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='introduce',
        ),
    ]
