# Generated by Django 5.0.7 on 2024-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOARD', '0006_answer_recommender_question_recommender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='introduce',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='유저이미지'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscript',
            field=models.CharField(blank=True, max_length=200, verbose_name='유저소개문'),
        ),
    ]
